#!/bin/bash

REGEX='\([0-9]*\)_TCP=tcp://\([0-9]\{1,3\}\.\)\{3\}\([0-9]\)\{1,3\}\:\([0-9]*\)'

MATCH="$(env | grep -o $REGEX | sed -e "s/_TCP=tcp:\/\// /" -e "s/:/ /" | awk '{ printf "HiddenServicePort %s %s:%s\n", $1, $2, $3 }')"

if [ ! -z "$MATCH" ]; then
  printf "Routing hidden service to:\n $MATCH";
  echo "$MATCH" >> /etc/torrc
fi

/usr/bin/tor -f /etc/torrc
